package com.iluwatar;

import java.util.ArrayList;
import java.util.List;

import org.apache.wicket.markup.html.WebMarkupContainer;
import org.apache.wicket.model.IModel;
import org.apache.wicket.request.mapper.parameter.PageParameters;

import com.iluwatar.foundation.blockgrid.BlockGridOptions;
import com.iluwatar.foundation.blockgrid.BlockGridType;
import com.iluwatar.foundation.blockgrid.FoundationBlockGrid;
import com.iluwatar.foundation.icon.FoundationIconType;
import com.iluwatar.foundation.icon.FoundationIconAndTextPanel;
import com.iluwatar.foundation.util.StringUtil;

public class FoundationIconsPage extends BasePage {

	private static final long serialVersionUID = 1L;

	public FoundationIconsPage(PageParameters params) {
		super(params);
		
		ArrayList<BlockGridOptions> optionsList = new ArrayList<>();
		optionsList.add(new BlockGridOptions(BlockGridType.SMALL_BLOCK_GRID, 2));
		optionsList.add(new BlockGridOptions(BlockGridType.LARGE_BLOCK_GRID, 4));
		
		ArrayList<FoundationIconType> generalIconsDataList = new ArrayList<>();
		generalIconsDataList.add(FoundationIconType.HEART);
		generalIconsDataList.add(FoundationIconType.STAR);
		generalIconsDataList.add(FoundationIconType.PLUS);
		generalIconsDataList.add(FoundationIconType.MINUS);
		generalIconsDataList.add(FoundationIconType.X);
		generalIconsDataList.add(FoundationIconType.CHECK);
		generalIconsDataList.add(FoundationIconType.UPLOAD);
		generalIconsDataList.add(FoundationIconType.DOWNLOAD);
		generalIconsDataList.add(FoundationIconType.WIDGET);
		generalIconsDataList.add(FoundationIconType.MARKER);
		generalIconsDataList.add(FoundationIconType.TRASH);
		generalIconsDataList.add(FoundationIconType.PAPERCLIP);
		generalIconsDataList.add(FoundationIconType.LOCK);
		generalIconsDataList.add(FoundationIconType.UNLOCK);
		generalIconsDataList.add(FoundationIconType.CALENDAR);
		generalIconsDataList.add(FoundationIconType.CLOUD);
		generalIconsDataList.add(FoundationIconType.MAGNIFYING_GLASS);
		generalIconsDataList.add(FoundationIconType.ZOOM_OUT);
		generalIconsDataList.add(FoundationIconType.ZOOM_IN);
		generalIconsDataList.add(FoundationIconType.WRENCH);
		generalIconsDataList.add(FoundationIconType.RSS);
		generalIconsDataList.add(FoundationIconType.SHARE);
		generalIconsDataList.add(FoundationIconType.FLAG);
		generalIconsDataList.add(FoundationIconType.LIST_THUMBNAILS);
		generalIconsDataList.add(FoundationIconType.LIST);
		generalIconsDataList.add(FoundationIconType.THUMBNAILS);
		generalIconsDataList.add(FoundationIconType.ANNOTATE);
		generalIconsDataList.add(FoundationIconType.FOLDER);
		generalIconsDataList.add(FoundationIconType.FOLDER_LOCK);
		generalIconsDataList.add(FoundationIconType.FOLDER_ADD);
		generalIconsDataList.add(FoundationIconType.CLOCK);
		generalIconsDataList.add(FoundationIconType.PLAY_VIDEO);
		generalIconsDataList.add(FoundationIconType.CROP);
		generalIconsDataList.add(FoundationIconType.ARCHIVE);
		generalIconsDataList.add(FoundationIconType.PENCIL);
		generalIconsDataList.add(FoundationIconType.GRAPH_TREND);
		generalIconsDataList.add(FoundationIconType.GRAPH_BAR);
		generalIconsDataList.add(FoundationIconType.GRAPH_HORIZONTAL);
		generalIconsDataList.add(FoundationIconType.GRAPH_PIE);
		generalIconsDataList.add(FoundationIconType.CHECKBOX);
		generalIconsDataList.add(FoundationIconType.MINUS_CIRCLE);
		generalIconsDataList.add(FoundationIconType.X_CIRCLE);
		generalIconsDataList.add(FoundationIconType.EYE);
		generalIconsDataList.add(FoundationIconType.DATABASE);
		generalIconsDataList.add(FoundationIconType.RESULTS);
		generalIconsDataList.add(FoundationIconType.RESULTS_DEMOGRAPHICS);
		generalIconsDataList.add(FoundationIconType.LIKE);
		generalIconsDataList.add(FoundationIconType.DISLIKE);
		generalIconsDataList.add(FoundationIconType.UPLOAD_CLOUD);
		generalIconsDataList.add(FoundationIconType.CAMERA);
		generalIconsDataList.add(FoundationIconType.ALERT);
		generalIconsDataList.add(FoundationIconType.BOOKMARK);
		generalIconsDataList.add(FoundationIconType.CONTRAST);
		generalIconsDataList.add(FoundationIconType.MAIL);
		generalIconsDataList.add(FoundationIconType.VIDEO);
		generalIconsDataList.add(FoundationIconType.TELEPHONE);
		generalIconsDataList.add(FoundationIconType.COMMENT);
		generalIconsDataList.add(FoundationIconType.COMMENT_VIDEO);
		generalIconsDataList.add(FoundationIconType.COMMENT_QUOTES);
		generalIconsDataList.add(FoundationIconType.COMMENT_MINUS);
		generalIconsDataList.add(FoundationIconType.MEGAPHONE);
		generalIconsDataList.add(FoundationIconType.SOUND);
		generalIconsDataList.add(FoundationIconType.ADDRESS_BOOK);
		generalIconsDataList.add(FoundationIconType.BLUETOOTH);
		generalIconsDataList.add(FoundationIconType.HTML5);
		generalIconsDataList.add(FoundationIconType.CSS3);
		generalIconsDataList.add(FoundationIconType.LAYOUT);
		generalIconsDataList.add(FoundationIconType.WEB);
		generalIconsDataList.add(FoundationIconType.FOUNDATION);
		add(createBlockGrid("generalIcons", optionsList, generalIconsDataList));
		
		ArrayList<FoundationIconType> pageIconsDataList = new ArrayList<>();
		pageIconsDataList.add(FoundationIconType.PAGE);
		pageIconsDataList.add(FoundationIconType.PAGE_CSV);
		pageIconsDataList.add(FoundationIconType.PAGE_DOC);
		pageIconsDataList.add(FoundationIconType.PAGE_PDF);
		pageIconsDataList.add(FoundationIconType.PAGE_EXPORT);
		pageIconsDataList.add(FoundationIconType.PAGE_EXPORT_CSV);
		pageIconsDataList.add(FoundationIconType.PAGE_EXPORT_DOC);
		pageIconsDataList.add(FoundationIconType.PAGE_EXPORT_PDF);
		pageIconsDataList.add(FoundationIconType.PAGE_ADD);
		pageIconsDataList.add(FoundationIconType.PAGE_REMOVE);
		pageIconsDataList.add(FoundationIconType.PAGE_DELETE);
		pageIconsDataList.add(FoundationIconType.PAGE_EDIT);
		pageIconsDataList.add(FoundationIconType.PAGE_SEARCH);
		pageIconsDataList.add(FoundationIconType.PAGE_COPY);
		pageIconsDataList.add(FoundationIconType.PAGE_FILLED);
		pageIconsDataList.add(FoundationIconType.PAGE_MULTIPLE);
		add(createBlockGrid("pageIcons", optionsList, pageIconsDataList));
		
		ArrayList<FoundationIconType> arrowIconsDataList = new ArrayList<>();
		arrowIconsDataList.add(FoundationIconType.ARROW_UP);
		arrowIconsDataList.add(FoundationIconType.ARROW_RIGHT);
		arrowIconsDataList.add(FoundationIconType.ARROW_DOWN);
		arrowIconsDataList.add(FoundationIconType.ARROW_LEFT);
		arrowIconsDataList.add(FoundationIconType.ARROWS_OUT);
		arrowIconsDataList.add(FoundationIconType.ARROWS_IN);
		arrowIconsDataList.add(FoundationIconType.ARROWS_EXPAND);
		arrowIconsDataList.add(FoundationIconType.ARROWS_COMPRESS);
		add(createBlockGrid("arrowIcons", optionsList, arrowIconsDataList));
		
		ArrayList<FoundationIconType> peopleIconsDataList = new ArrayList<>();
		peopleIconsDataList.add(FoundationIconType.TORSO);
		peopleIconsDataList.add(FoundationIconType.TORSO_FEMALE);
		peopleIconsDataList.add(FoundationIconType.TORSOS);
		peopleIconsDataList.add(FoundationIconType.TORSOS_FEMALE_MALE);
		peopleIconsDataList.add(FoundationIconType.TORSOS_MALE_FEMALE);
		peopleIconsDataList.add(FoundationIconType.TORSOS_ALL);
		peopleIconsDataList.add(FoundationIconType.TORSOS_ALL_FEMALE);
		peopleIconsDataList.add(FoundationIconType.TORSO_BUSINESS);
		add(createBlockGrid("peopleIcons", optionsList, peopleIconsDataList));
		
		ArrayList<FoundationIconType> deviceIconsDataList = new ArrayList<>();
		deviceIconsDataList.add(FoundationIconType.MONITOR);
		deviceIconsDataList.add(FoundationIconType.LAPTOP);
		deviceIconsDataList.add(FoundationIconType.TABLET_PORTRAIT);
		deviceIconsDataList.add(FoundationIconType.TABLET_LANDSCAPE);
		deviceIconsDataList.add(FoundationIconType.MOBILE);
		deviceIconsDataList.add(FoundationIconType.MOBILE_SIGNAL);
		deviceIconsDataList.add(FoundationIconType.USB);
		add(createBlockGrid("deviceIcons", optionsList, deviceIconsDataList));
		
		ArrayList<FoundationIconType> textEditorIconsDataList = new ArrayList<>();
		textEditorIconsDataList.add(FoundationIconType.BOLD);
		textEditorIconsDataList.add(FoundationIconType.ITALIC);
		textEditorIconsDataList.add(FoundationIconType.UNDERLINE);
		textEditorIconsDataList.add(FoundationIconType.STRIKETHROUGH);
		textEditorIconsDataList.add(FoundationIconType.TEXT_COLOR);
		textEditorIconsDataList.add(FoundationIconType.BACKGROUND_COLOR);
		textEditorIconsDataList.add(FoundationIconType.SUPERSCRIPT);
		textEditorIconsDataList.add(FoundationIconType.SUBSCRIPT);
		textEditorIconsDataList.add(FoundationIconType.ALIGN_LEFT);
		textEditorIconsDataList.add(FoundationIconType.ALIGN_CENTER);
		textEditorIconsDataList.add(FoundationIconType.ALIGN_RIGHT);
		textEditorIconsDataList.add(FoundationIconType.ALIGN_JUSTIFY);
		textEditorIconsDataList.add(FoundationIconType.LIST_NUMBERED);
		textEditorIconsDataList.add(FoundationIconType.LIST_BULLET);
		textEditorIconsDataList.add(FoundationIconType.INDENT_MORE);
		textEditorIconsDataList.add(FoundationIconType.INDENT_LESS);
		textEditorIconsDataList.add(FoundationIconType.PRINT);
		textEditorIconsDataList.add(FoundationIconType.SAVE);
		textEditorIconsDataList.add(FoundationIconType.PHOTO);
		textEditorIconsDataList.add(FoundationIconType.FILTER);
		textEditorIconsDataList.add(FoundationIconType.PAINT_BUCKET);
		textEditorIconsDataList.add(FoundationIconType.LINK);
		textEditorIconsDataList.add(FoundationIconType.UNLINK);
		textEditorIconsDataList.add(FoundationIconType.QUOTE);
		add(createBlockGrid("textEditorIcons", optionsList, textEditorIconsDataList));

		ArrayList<FoundationIconType> mediaControlIconsDataList = new ArrayList<>();
		mediaControlIconsDataList.add(FoundationIconType.PLAY);
		mediaControlIconsDataList.add(FoundationIconType.STOP);
		mediaControlIconsDataList.add(FoundationIconType.PAUSE);
		mediaControlIconsDataList.add(FoundationIconType.PREVIOUS);
		mediaControlIconsDataList.add(FoundationIconType.REWIND);
		mediaControlIconsDataList.add(FoundationIconType.FAST_FORWARD);
		mediaControlIconsDataList.add(FoundationIconType.NEXT);
		mediaControlIconsDataList.add(FoundationIconType.RECORD);
		mediaControlIconsDataList.add(FoundationIconType.PLAY_CIRCLE);
		mediaControlIconsDataList.add(FoundationIconType.VOLUME_NONE);
		mediaControlIconsDataList.add(FoundationIconType.VOLUME);
		mediaControlIconsDataList.add(FoundationIconType.VOLUME_STRIKE);
		mediaControlIconsDataList.add(FoundationIconType.LOOP);
		mediaControlIconsDataList.add(FoundationIconType.SHUFFLE);
		mediaControlIconsDataList.add(FoundationIconType.EJECT);
		mediaControlIconsDataList.add(FoundationIconType.REWIND_TEN);
		add(createBlockGrid("mediaControlIcons", optionsList, mediaControlIconsDataList));

		ArrayList<FoundationIconType> eCommerceIconsDataList = new ArrayList<>();
		eCommerceIconsDataList.add(FoundationIconType.DOLLAR);
		eCommerceIconsDataList.add(FoundationIconType.EURO);
		eCommerceIconsDataList.add(FoundationIconType.POUND);
		eCommerceIconsDataList.add(FoundationIconType.YEN);
		eCommerceIconsDataList.add(FoundationIconType.BITCOIN);
		eCommerceIconsDataList.add(FoundationIconType.BITCOIN_CIRCLE);
		eCommerceIconsDataList.add(FoundationIconType.CREDIT_CARD);
		eCommerceIconsDataList.add(FoundationIconType.SHOPPING_CART);
		eCommerceIconsDataList.add(FoundationIconType.BURST);
		eCommerceIconsDataList.add(FoundationIconType.BURST_NEW);
		eCommerceIconsDataList.add(FoundationIconType.BURST_SALE);
		eCommerceIconsDataList.add(FoundationIconType.PAYPAL);
		eCommerceIconsDataList.add(FoundationIconType.PRICE_TAG);
		eCommerceIconsDataList.add(FoundationIconType.PRICETAG_MULTIPLE);
		eCommerceIconsDataList.add(FoundationIconType.SHOPPING_BAG);
		eCommerceIconsDataList.add(FoundationIconType.DOLLAR_BILL);
		add(createBlockGrid("eCommerceIcons", optionsList, eCommerceIconsDataList));

		ArrayList<FoundationIconType> accessibilityIconsDataList = new ArrayList<>();
		accessibilityIconsDataList.add(FoundationIconType.WHEELCHAIR);
		accessibilityIconsDataList.add(FoundationIconType.BRAILLE);
		accessibilityIconsDataList.add(FoundationIconType.CLOSED_CAPTION);
		accessibilityIconsDataList.add(FoundationIconType.BLIND);
		accessibilityIconsDataList.add(FoundationIconType.ASL);
		accessibilityIconsDataList.add(FoundationIconType.HEARING_AID);
		accessibilityIconsDataList.add(FoundationIconType.GUIDE_DOG);
		accessibilityIconsDataList.add(FoundationIconType.UNIVERSAL_ACCESS);
		accessibilityIconsDataList.add(FoundationIconType.TELEPHONE_ACCESSIBLE);
		accessibilityIconsDataList.add(FoundationIconType.ELEVATOR);
		accessibilityIconsDataList.add(FoundationIconType.MALE);
		accessibilityIconsDataList.add(FoundationIconType.FEMALE);
		accessibilityIconsDataList.add(FoundationIconType.MALE_FEMALE);
		accessibilityIconsDataList.add(FoundationIconType.MALE_SYMBOL);
		accessibilityIconsDataList.add(FoundationIconType.FEMALE_SYMBOL);
		add(createBlockGrid("accessibilityIcons", optionsList, accessibilityIconsDataList));

		ArrayList<FoundationIconType> socialIconsDataList = new ArrayList<>();
		socialIconsDataList.add(FoundationIconType.SOCIAL_500PX);
		socialIconsDataList.add(FoundationIconType.SOCIAL_ADOBE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_AMAZON);
		socialIconsDataList.add(FoundationIconType.SOCIAL_ANDROID);
		socialIconsDataList.add(FoundationIconType.SOCIAL_APPLE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_BEHANCE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_BING);
		socialIconsDataList.add(FoundationIconType.SOCIAL_BLOGGER);
		socialIconsDataList.add(FoundationIconType.SOCIAL_DELICIOUS);
		socialIconsDataList.add(FoundationIconType.SOCIAL_DESIGNER_NEWS);
		socialIconsDataList.add(FoundationIconType.SOCIAL_DEVIANT_ART);
		socialIconsDataList.add(FoundationIconType.SOCIAL_DIGG);
		socialIconsDataList.add(FoundationIconType.SOCIAL_DRIBBBLE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_DRIVE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_DROPBOX);
		socialIconsDataList.add(FoundationIconType.SOCIAL_EVERNOTE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_FACEBOOK);
		socialIconsDataList.add(FoundationIconType.SOCIAL_FLICKR);
		socialIconsDataList.add(FoundationIconType.SOCIAL_FORRST);
		socialIconsDataList.add(FoundationIconType.SOCIAL_FOURSQUARE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_GAME_CENTER);
		socialIconsDataList.add(FoundationIconType.SOCIAL_GITHUB);
		socialIconsDataList.add(FoundationIconType.SOCIAL_GOOGLE_PLUS);
		socialIconsDataList.add(FoundationIconType.SOCIAL_HACKER_NEWS);
		socialIconsDataList.add(FoundationIconType.SOCIAL_HI5);
		socialIconsDataList.add(FoundationIconType.SOCIAL_INSTAGRAM);
		socialIconsDataList.add(FoundationIconType.SOCIAL_JOOMLA);
		socialIconsDataList.add(FoundationIconType.SOCIAL_LASTFM);
		socialIconsDataList.add(FoundationIconType.SOCIAL_MYSPACE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_ORKUT);
		socialIconsDataList.add(FoundationIconType.SOCIAL_PATH);
		socialIconsDataList.add(FoundationIconType.SOCIAL_PICASA);
		socialIconsDataList.add(FoundationIconType.SOCIAL_PINTEREST);
		socialIconsDataList.add(FoundationIconType.SOCIAL_RDIO);
		socialIconsDataList.add(FoundationIconType.SOCIAL_REDDIT);
		socialIconsDataList.add(FoundationIconType.SOCIAL_SKYPE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_SKILLSHARE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_SMASHING_MAG);
		socialIconsDataList.add(FoundationIconType.SOCIAL_SNAPCHAT);
		socialIconsDataList.add(FoundationIconType.SOCIAL_SPOTIFY);
		socialIconsDataList.add(FoundationIconType.SOCIAL_SQUIDOO);
		socialIconsDataList.add(FoundationIconType.SOCIAL_STACK_OVERFLOW);
		socialIconsDataList.add(FoundationIconType.SOCIAL_STEAM);
		socialIconsDataList.add(FoundationIconType.SOCIAL_STUMBLEUPON);
		socialIconsDataList.add(FoundationIconType.SOCIAL_TREEHOUSE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_TUMBLR);
		socialIconsDataList.add(FoundationIconType.SOCIAL_TWITTER);
		socialIconsDataList.add(FoundationIconType.SOCIAL_VIMEO);
		socialIconsDataList.add(FoundationIconType.SOCIAL_WINDOWS);
		socialIconsDataList.add(FoundationIconType.SOCIAL_XBOX);
		socialIconsDataList.add(FoundationIconType.SOCIAL_YAHOO);
		socialIconsDataList.add(FoundationIconType.SOCIAL_YELP);
		socialIconsDataList.add(FoundationIconType.SOCIAL_YOUTUBE);
		socialIconsDataList.add(FoundationIconType.SOCIAL_ZERPLY);
		socialIconsDataList.add(FoundationIconType.SOCIAL_ZURB);
		add(createBlockGrid("socialIcons", optionsList, socialIconsDataList));

		ArrayList<FoundationIconType> miscIconsDataList = new ArrayList<>();
		miscIconsDataList.add(FoundationIconType.COMPASS);
		miscIconsDataList.add(FoundationIconType.MUSIC);
		miscIconsDataList.add(FoundationIconType.LIGHTBULB);
		miscIconsDataList.add(FoundationIconType.BATTERY_FULL);
		miscIconsDataList.add(FoundationIconType.BATTERY_HALF);
		miscIconsDataList.add(FoundationIconType.BATTERY_EMPTY);
		miscIconsDataList.add(FoundationIconType.PROJECTION_SCREEN);
		miscIconsDataList.add(FoundationIconType.INFO);
		miscIconsDataList.add(FoundationIconType.POWER);
		miscIconsDataList.add(FoundationIconType.ASTERISK);
		miscIconsDataList.add(FoundationIconType.AT_SIGN);
		miscIconsDataList.add(FoundationIconType.KEY);
		miscIconsDataList.add(FoundationIconType.TICKET);
		miscIconsDataList.add(FoundationIconType.BOOK);
		miscIconsDataList.add(FoundationIconType.BOOK_BOOKMARK);
		miscIconsDataList.add(FoundationIconType.ANCHOR);
		miscIconsDataList.add(FoundationIconType.PUZZLE);
		miscIconsDataList.add(FoundationIconType.FOOT);
		miscIconsDataList.add(FoundationIconType.PAW);
		miscIconsDataList.add(FoundationIconType.MOUNTAINS);
		miscIconsDataList.add(FoundationIconType.FIRST_AID);
		miscIconsDataList.add(FoundationIconType.TROPHY);
		miscIconsDataList.add(FoundationIconType.PROHIBITED);
		miscIconsDataList.add(FoundationIconType.NO_DOGS);
		miscIconsDataList.add(FoundationIconType.NO_SMOKING);
		miscIconsDataList.add(FoundationIconType.SAFETY_CONE);
		miscIconsDataList.add(FoundationIconType.SHIELD);
		miscIconsDataList.add(FoundationIconType.CROWN);
		miscIconsDataList.add(FoundationIconType.TARGET);
		miscIconsDataList.add(FoundationIconType.TARGET_TWO);
		miscIconsDataList.add(FoundationIconType.DIE_ONE);
		miscIconsDataList.add(FoundationIconType.DIE_TWO);
		miscIconsDataList.add(FoundationIconType.DIE_THREE);
		miscIconsDataList.add(FoundationIconType.DIE_FOUR);
		miscIconsDataList.add(FoundationIconType.DIE_FIVE);
		miscIconsDataList.add(FoundationIconType.DIE_SIX);
		miscIconsDataList.add(FoundationIconType.SKULL);
		miscIconsDataList.add(FoundationIconType.MAP);
		miscIconsDataList.add(FoundationIconType.CLIPBOARD);
		miscIconsDataList.add(FoundationIconType.CLIPBOARD_PENCIL);
		miscIconsDataList.add(FoundationIconType.CLIPBOARD_NOTES);
		add(createBlockGrid("miscIcons", optionsList, miscIconsDataList));
	}
	
	FoundationBlockGrid<FoundationIconType> createBlockGrid(String id, List<BlockGridOptions> optionsList, List<FoundationIconType> dataList) {
		return new FoundationBlockGrid<FoundationIconType>(id, optionsList, dataList) {

			private static final long serialVersionUID = 1L;

			@Override
			public WebMarkupContainer createContent(int idx, String id,
					IModel<FoundationIconType> model) {
				return new FoundationIconAndTextPanel(id, model.getObject(), StringUtil.EnumNameToCssClassName(model.getObject().name()));
			}
		};
	}
}
